


```{r}
metrics <- read.csv2("output/patient_metrics_2023-05-25_12-47-35_flattened.csv")
```

Percentage of target dose matches journal

```{r} 
target_dose_correct <- metrics$target_dose_correct == "True"
mean(target_dose_correct)
```


Percentage of correct "visual scoring"-type recurrence type guesses
```{r}
recurrence_type_correct <- metrics$recurrence_type_correct == "True"
mean(recurrence_type_correct)
```

Confusion matrix for "visual scoring"-type recurrence type guesses
```{r}
library(cvms)
library(dplyr)

t <- metrics$ProgressionType
targets <- t %>% 
  replace(t == 1, "Local-only") %>% 
  replace(t == 2, "Combined") %>% 
  replace(t == 3, "Non-local")
p <- metrics$recurrence_type_guess

predictions <- p %>% 
  replace(p == 1, "Local-only") %>% 
  replace(p == 2, "Combined") %>% 
  replace(p == 3, "Non-local") 


conf_mat <- confusion_matrix(targets = targets,
                             predictions = predictions)

plot_confusion_matrix(conf_mat$`Confusion Matrix`[[1]], add_sums=TRUE)
```

Summary of classical recurrence type predictions
```{r}
classical_type <- metrics$classical_recurrence_type
tbl <- table(classical_type)
bigtbl <- cbind(tbl, prop.table(tbl) * 100)
colnames(bigtbl) <- c("n", "Percentage")
bigtbl
```
