featureClass:
    glrlm: [RunLengthNonUniformity]
    glcm: [Contrast, Correlation]

setting:
    correctMask: True # Images have Geometry mismatch error. This fixes it, but we should consider investigating why the error happens. Error does not happen for patient 0361