# Settings given to the pyradiomics feature extractor upon initialization. 
# See pyradiomics documentation for further details.

setting:
    correctMask: True 
# Some images have 'Geometry mismatch error'. 
# This error has been fixed, but the setting will be kept enabled, 
# to prevent potential issues with other images in the future.